# ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
# │  used properties are included. For a list of all supported properties and their functions,     │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.uv.immunization-incubator
canonical: http://hl7.org/fhir/uv/immunization-incubator
name: ImmunizationAdditionalResources
title: Immunization Incubator Implementation Guide
description: A guide that defines ImmunizationEvaluation and ImmunizationRecommendation as Additional Resources in FHIR
status: active # draft | active | retired | unknown
version: 0.1.0
fhirVersion: 6.0.0-ballot3
copyrightYear: 2025+
releaseLabel: ci-build
license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#001 "World" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: HL7 International / Public Health
  url: http://www.hl7.org/Special/committees/pher
  email: pher@lists.HL7.org
extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    valueCode: trial-use
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm
    valueInteger: 3
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg
    valueCode: pher

definition:
  extension: 
    - url: http://hl7.org/fhir/tools/StructureDefinition/ig-link-dependency
      valueCode: hl7.fhir.r5.examples

# dependencies:

parameters:
  path-resource:
    - input/resources/immunizationevaluation
    - input/resources/immunizationrecommendation
  additional-resource:
    - input/resources/immunizationevaluation/StructureDefinition-ImmunizationEvaluation.xml
    - input/resources/immunizationrecommendation/StructureDefinition-ImmunizationRecommendation.xml
  special-url-base: http://hl7.org/fhir
  pin-canonicals: pin-multiples

resources:
  ImmunizationEvaluation/immunization-evaluation-invalid:
    name: ImmunizationEvaluation - Invalid Example 
    description: An example of an administration event which was found to be invalid.
    exampleBoolean: true
  ImmunizationEvaluation/immunization-evaluation-valid:
    name: ImmunizationEvaluation - Valid Example
    description: An example of an administration event which was found to be valid.
    exampleBoolean: true
  ImmunizationRecommendation/immunization-recommendation-by-target-disease:
    name: ImmunizationRecommendation - By Target Disease Example
    description: An example of an immunization recommendation by target disease.
    exampleBoolean: true
  ImmunizationRecommendation/immunization-recommendation-by-vaccine-code:
    name: ImmunizationRecommendation - By Vaccine Code Example
    description: An example of an immunization recommendation by vaccine code.
    exampleBoolean: true

pages:
  index.md:
    title: IG Home
  changes.md:
    title: Change Log
  background.md:
    title: Background

menu:
  Home: index.html
  Background: background.html
  FHIR Artifacts: artifacts.html
#  Support:
#    Discussion Forum: https://chat.fhir.org/#channels/501058/Symptoms.20on.20FHIR
#    Project Dashboard: 
#    Propose a Change: 
  Change Log: changes.html
